# Lattice OCR Workers - Domain-agnostic OCR processing
#
# Run with New Relic logging:
#   docker compose -f lattice-ocr.yml -f newrelic-logging.yml up -d
#
# Workers:
#   - ocr-worker: Extracts text from images/PDFs using Tesseract OCR

x-common-env: &common-env
  NODE_ENV: production
  LOG_LEVEL: info
  LATTICE_TEAM: platform
  LATTICE_CLOUD: local
  LATTICE_REGION: local

x-kafka-env: &kafka-env
  KAFKA_BROKERS: ${KAFKA_BROKERS:-pkc-619z3.us-east1.gcp.confluent.cloud:9092}
  KAFKA_SSL: "true"
  KAFKA_SASL_MECHANISM: plain
  KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME:-}
  KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD:-}

x-postgres-env: &postgres-env
  DATABASE_URL: postgresql://lattice:${POSTGRES_PASSWORD:-lattice_dev_password}@${POSTGRES_HOST:-host.docker.internal}:${POSTGRES_PORT:-5432}/lattice

x-newrelic-env: &newrelic-env
  TELEMETRY_PROVIDER: ${TELEMETRY_PROVIDER:-newrelic}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED:-true}
  NEW_RELIC_LOG_LEVEL: ${NEW_RELIC_LOG_LEVEL:-info}
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  # Log forwarding handled by Fluent Bit (newrelic-logging.yml), not APM agent
  NEW_RELIC_APPLICATION_LOGGING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: "true"

x-storage-env: &storage-env
  S3_ENDPOINT: ${S3_ENDPOINT:-http://100.103.47.127:9000}
  S3_REGION: us-east-1
  S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-minioadmin}
  S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-minioadmin}
  S3_FORCE_PATH_STYLE: "true"

services:
  # ==========================================================================
  # OCR Worker
  # Consumes: lattice.ocr.request.v1
  # Produces: lattice.ocr.result.v1
  #
  # Domain-agnostic OCR service using Tesseract. Stores extracted text in
  # MinIO (claim-check pattern) and metadata in Postgres for idempotency.
  # ==========================================================================
  ocr-worker:
    build:
      context: ../../..
      dockerfile: apps/workers/ocr-worker/Dockerfile
    container_name: lattice-ocr-worker
    labels:
      com.newrelic.logs: "true"
    environment:
      <<: [*common-env, *kafka-env, *postgres-env, *storage-env, *newrelic-env]
      # Service identity (DD_SERVICE required by worker-base config schema)
      DD_SERVICE: lattice-worker-ocr
      DD_VERSION: "0.1.0"
      NEW_RELIC_APP_NAME: lattice-worker-ocr
      # Lattice context
      LATTICE_DOMAIN: ocr
      LATTICE_STAGE: extract
      # Kafka topics
      KAFKA_CLIENT_ID: ocr-worker
      KAFKA_GROUP_ID: ocr-worker-group
      KAFKA_TOPIC_IN: lattice.ocr.request.v1
      KAFKA_TOPIC_OUT: lattice.ocr.result.v1
      KAFKA_TOPIC_DLQ: lattice.dlq.ocr.v1
      # OCR text storage bucket
      S3_OCR_TEXT_BUCKET: ${S3_OCR_TEXT_BUCKET:-lattice-ocr-results}
      # Tesseract config
      TESSERACT_PATH: /usr/bin/tesseract
      TESSERACT_LANG: eng
      TESSERACT_DPI: "300"
      # Health
      HEALTH_PORT: 3000
    ports:
      - "3108:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - lattice-ocr-network

networks:
  lattice-ocr-network:
    driver: bridge
