# =============================================================================
# New Relic Logging Agent (Fluent Bit)
# =============================================================================
# Label-based opt-in log collection using Fluent Bit.
# Only containers with label `com.newrelic.logs: "true"` are collected.
#
# Usage (with main stack):
#   docker compose -f lattice-core.yml -f lattice-workers.yml -f newrelic-logging.yml up -d
#
# Usage (standalone, e.g., OCR server):
#   docker compose -f lattice-ocr.yml -f newrelic-logging.yml up -d
#
# Required environment variables:
#   NEW_RELIC_LICENSE_KEY - Your New Relic ingest license key
#
# Optional environment variables:
#   NEW_RELIC_REGION      - US (default) or EU
#   LATTICE_ENV           - Environment tag (default: local)
#   LOG_LEVEL             - Fluent Bit log level: error, warn, info, debug (default: info)
#
# To opt-in a container, add this label to its service:
#   labels:
#     com.newrelic.logs: "true"
#
# Note: Fluent Bit reads logs via Docker socket - no network connectivity to
# containers is required. It can run standalone on any Docker host.
# =============================================================================

services:
  newrelic-logs:
    image: fluent/fluent-bit:4.2.0
    container_name: lattice-newrelic-logs
    environment:
      # New Relic configuration
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
      NEW_RELIC_LOG_HOST: ${NEW_RELIC_REGION:-US} == "EU" && "log-api.eu.newrelic.com" || "log-api.newrelic.com"
      # Metadata
      LATTICE_ENV: ${LATTICE_ENV:-local}
      # Fluent Bit log level
      LOG_LEVEL: ${LOG_LEVEL:-info}
    # Entrypoint: set host based on region and validate license key
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        # Set New Relic log host based on region
        if [ "${NEW_RELIC_REGION:-US}" = "EU" ]; then
          export NEW_RELIC_LOG_HOST="log-api.eu.newrelic.com"
        else
          export NEW_RELIC_LOG_HOST="log-api.newrelic.com"
        fi

        # Warn if license key is missing (but don't crash - allows local testing)
        if [ -z "${NEW_RELIC_LICENSE_KEY}" ]; then
          echo "[WARNING] NEW_RELIC_LICENSE_KEY is not set. Logs will NOT be forwarded to New Relic."
          echo "[WARNING] Set NEW_RELIC_LICENSE_KEY in your .env file or environment to enable log forwarding."
          echo "[INFO] Fluent Bit will still run for local testing (collecting logs, but HTTP output will fail)."
        else
          echo "[INFO] New Relic logging configured for ${NEW_RELIC_REGION:-US} region (${NEW_RELIC_LOG_HOST})"
        fi

        exec /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    volumes:
      # Docker socket for container metadata enrichment
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Docker container logs
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Fluent Bit configuration
      - ./newrelic/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./newrelic/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    ports:
      - "2020:2020"  # Fluent Bit metrics endpoint
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2020/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    labels:
      project: lattice
      component: observability
